/**
 * Inlines asr/whisper.py into a TS module so `bun build --compile` carries it
 * inside the binary. At runtime the CLI writes it to a cache dir and hands the
 * path to `uv run --script`.
 *
 * Generated file is gitignored: asr/whisper.py is the source of truth.
 */
import { $ } from "bun";

const src = await Bun.file("asr/whisper.py").text();
const hash = Bun.hash(src).toString(16);

const out = `// GENERATED by scripts/embed-asr.ts -- do not edit.
// Source: asr/whisper.py
export const ASR_SCRIPT = ${JSON.stringify(src)};
export const ASR_HASH = ${JSON.stringify(hash)};
`;

await Bun.write("src/asr-embedded.ts", out);
console.log(`embedded asr/whisper.py (${src.length} bytes, hash ${hash})`);
